# Generated by Django 6.0.6 on 2026-06-07 20:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Фото категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название работы')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Фото торта')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Детали (вес, декор)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Работа в портфолио',
                'verbose_name_plural': 'Портфолио',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание начинки и состава')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за кг')),
                ('min_weight', models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=4, verbose_name='Минимальный вес (кг)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Главное фото')),
                ('is_allergen_free', models.BooleanField(default=False, verbose_name='Без аллергенов/глютена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Начинка / Десерт',
                'verbose_name_plural': 'Начинки / Десерты',
            },
        ),
    ]
