# Generated by Django 6.0.6 on 2026-06-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='url',
            field=models.URLField(default='', max_length=500, verbose_name='Ссылка на фото'),
        ),
    ]
