# Generated by Django 6.0.6 on 2026-06-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_productimage_image_productimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Ссылка на фото'),
        ),
    ]
