# Generated by Django 6.0.6 on 2026-06-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productimage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.URLField(default=2, max_length=500, verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
