# Generated by Django 6.0.6 on 2026-06-17 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_product_stock_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('flavor', 'Вкус / начинка'), ('purpose', 'Назначение'), ('feature', 'Особенности'), ('format', 'Размер / формат'), ('decor', 'Декор'), ('season', 'Сезон')], max_length=20, unique=True, verbose_name='Тип группы')),
            ],
            options={
                'verbose_name': 'Группа тегов',
                'verbose_name_plural': 'Группы тегов',
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['group', 'name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='catalog.taggroup', verbose_name='Группа'),
        ),
    ]
