# Generated by Django 6.0.6 on 2026-06-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_taggroup_alter_tag_options_tag_group'),
    ]

    operations = [
    ]
