# Generated by Django 6.0.6 on 2026-06-21 13:09

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_category_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Медиафайл товара', 'verbose_name_plural': 'Медиафайлы товаров'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=catalog.models.product_video_upload_path, verbose_name='Видео (MP4)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt-текст / подпись'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.product_image_upload_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главный медиафайл'),
        ),
    ]
