# Generated by Django 6.0.6 on 2026-06-07 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('event_date', models.DateField(verbose_name='Дата мероприятия')),
                ('estimated_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Желаемый вес (кг)')),
                ('comment', models.TextField(blank=True, verbose_name='Пожелания по декору и надписи')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('contacted', 'Связались с клиентом'), ('confirmed', 'Подтвержден (предоплата)'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Интересующая начинка')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
